# Generated by Django 6.0.1 on 2026-01-08 14:50

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_rename_date_time_review_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_date',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None),
        ),
    ]
