# Generated by Django 6.0.1 on 2026-01-10 17:11

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_rename_created_date_review_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='postal_code',
            new_name='postel_code',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='date_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='register_date',
            new_name='register_data',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_image',
        ),
        migrations.AddField(
            model_name='country',
            name='country_img',
            field=models.ImageField(default='', upload_to='country_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='booking_app.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_hotel', to='booking_app.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован'), ('Свободен', 'Свободен')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status_en',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован'), ('Свободен', 'Свободен')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status_ru',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован'), ('Свободен', 'Свободен')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.CreateModel(
            name='HotelImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_img', models.ImageField(upload_to='hotel_photo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='booking_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='booking_app.room')),
            ],
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
        migrations.AddField(
            model_name='room',
            name='Room_type',
            field=models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Семеный', 'Семеный'), ('Эконом', 'Эконом'), ('Одноместный', 'Одноместный')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
