# Generated by Django 6.0.1 on 2026-01-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_remove_roomimage_room_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelImg',
            new_name='HotelImage',
        ),
        migrations.RenameModel(
            old_name='RoomImg',
            new_name='RoomImage',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_img',
            new_name='country_image',
        ),
        migrations.RenameField(
            model_name='hotelimage',
            old_name='hotel_img',
            new_name='hotel_image',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Room_type',
            new_name='room_type',
        ),
    ]
